name: Integrate

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Project
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

  # lint:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run Linter

  #       uses: github/super-linter@v5.2.1
  #       env:
  #         VALIDATE_ALL_CODEBASE: true
  #         VALIDATE_JAVASCRIPT_ES: true
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         LINTER_RULES_PATH: /
