name: Integrate

on: [push]

jobs:
  build:
    name: Run linter and build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Project
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build # also runs linter
